name: Install
description: "steps up Node.js and runs install"

runs:
  using: composite
  steps:
    - name: Install dependencies
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "kiu.manoguerra@gmail.com"
        git config --global user.user "lucas manoguerra"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
