name: Lint and Format with Tests

on:
  push:
    branches:
      - master # Cambia esto según la rama que quieras monitorear

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: './.github/common/first-install'

      - name: Lint and Format
        run: |
          pnpm run lint
          pnpm format:write

      - name: Executing Tests
        run: |
          pnpm test

      - name: Complete
        run: echo "Linting and formatting and tests with tests completed"
