name: Build. Test and Release

concurrency: master

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.version.output.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SERVICE_ACCOUNT_PAT }}

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Enable node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Version Command
        id: version
        run: |
          pnpm install -g @changesets/cli
          echo ::set-output name=changes::$(npx changeset version 2>&1 | grep -q 'No unreleased changesets found' && echo 'false' || echo 'true')

      - name: Push changes
        if: steps.version.outputs.changes == 'true'
        run: |
          git config user.name "lucas manoguerra"
          git config user.email "kiu.manoguerra@gmail.com"
          git add -A
          git commit -m "Version packages" || echo "No changes to commit"
          git push
    
  build:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Enable node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          scope: '@uiinspire'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}

      - name: Install dependencies
        id: changeset
        run: |
          pnpm install

      - name: Release packages
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PAT }}
